feat: dev container provides hcloud cli

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -8,7 +8,15 @@
 #
 FROM docker.io/python:trixie
 
-ARG ARCH=aarch64
+# Valid options are:
+#   - amd64 (Intel / AMD)
+#   - arm64 (Apple Silicon / ARM)
+#
+ARG ARCH=arm64
+
+RUN if [ "${ARCH}" != "arm64" ] && [ "${ARCH}" != "amd64" ]; then \
+    echo "Error: ARCH must be either arm64 or amd64" && exit 1; \
+fi
 
 RUN apt-get update \
     && apt-get install -y --no-install-recommends \
@@ -25,11 +33,16 @@ RUN apt-get update \
  #   - [AWS CLI install and update instructions](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html)
  #
  COPY awscliv2-public-key.asc /tmp/aws/awscliv2-public-key.asc
- RUN gpg --import /tmp/aws/awscliv2-public-key.asc \
+ RUN if [ "${ARCH}" = "arm64" ] ; then \
+        AWS_ARCH="aarch64" ; \
+    else \
+        AWS_ARCH="x86_64" ; \
+    fi \
+    && gpg --import /tmp/aws/awscliv2-public-key.asc \
     && mkdir -p /tmp/awscli \
     && cd /tmp/awscli \
-    && curl -o "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-${ARCH}.zip" \
-    && curl -o "awscliv2.sig" "https://awscli.amazonaws.com/awscli-exe-linux-${ARCH}.zip.sig" \
+    && curl -o "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-${AWS_ARCH}.zip" \
+    && curl -o "awscliv2.sig" "https://awscli.amazonaws.com/awscli-exe-linux-${AWS_ARCH}.zip.sig" \
     && ls -la awscliv2.* \
     && gpg --verify --trust-model always awscliv2.sig awscliv2.zip \
     && unzip awscliv2.zip \
@@ -37,3 +50,16 @@ RUN apt-get update \
     && cd /root \
     && rm -rf /tmp/awscli \
     && aws --version
+
+# Install Hetzner hcloud CLI
+#
+# Documentation:
+#   - [hcloud CLI GitHub repository](https://github.com/hetznercloud/cli)
+#
+RUN mkdir -p /root/hcloud \
+    && cd /root/hcloud \
+    && wget "https://github.com/hetznercloud/cli/releases/download/v1.60.0/hcloud-linux-${ARCH}.tar.gz" -O "hcloud.tar.gz" \
+    && tar -xvzf hcloud.tar.gz \
+    && ln -s /root/hcloud/hcloud /usr/local/bin/hcloud \
+    && cd /root \
+    && hcloud version
